---
title: "Flat files, csv and delimeted"
output: html_notebook
---
Load readr from tidyverse.
```{r}
library(readr)
```
#.csv
```{r}
dog_bites <- read_csv("data/dog_bites.csv")
#there is a function read.csv(), but read_csv is better
```
```{r}
head(dog_bites)
summary(dog_bites)
```
#.txt

##tab separated
```{r}
bands <- read_tsv("data/indie_bands.txt")
head(bands)
```
##delimeter
```{r}
beer <- read_delim("data/beer.txt", delim = ";", n_max = 10)
beer_limited <- read_delim("data/beer.txt", delim = ";", n_max = 2)#specified number of rows to load with n_max
head(beer)
beer_limited
```
##fixed width separator(table) from txt
```{r}
max_temp <- read_table("data/maxtemp.txt")
head(max_temp)
#View(max_temp)
```
##reading files with extra stuff before the data - use skip = x,
```{r}
play_areas <- read_csv("data/play_areas.csv", skip = 3)
head(play_areas)
```
#specify col names 
```{r}
tv <- read_tsv("data/tv.txt", col_names = c("1", "2", "3", "4"))
head(tv)
```
#read url
```{r}
weekly_sst <- read_table("https://www.cpc.ncep.noaa.gov/data/indices/wksst8110.for",
                         skip = 4, 
                         col_names = c("Nino1+2",	"Nino3",	"Nino34"))
head(weekly_sst)
```
#rows(lines) separated text
```{r}
surnames <- read_lines("data/surnames.txt")
length(surnames)
```
```{r}
library(CodeClanData)
```
```{r}
library(readxl)
#write_csv("example/students.csv")
```
##specifying excel sheets
```{r}
seedmix <- read_xlsx("2_excel_files/data/edinburgh_seedmix.xlsx", sheet=4)
seedmix
```
```{r}
install.packages("openxlsx")
library(openxlsx)
```
```{r}
write.xlsx(students, file = "students.xlsx", colNames = TRUE, borders = "columns")
```
```{r}
students <- read_xlsx("students.xlsx")
students
```

#JSON files
```{r}
#library pacman allows to load mutiple libraries in a single statement
#install.packages("pacman")
##pacman::p_load(jsonlite, readr)
library(jsonlite)
library(readr)
```
```{r}
raw_colours <- read_file("3_json_files/data/colours.json")
raw_colours

```
```{r}
prettify(raw_colours)
```
```{r}
colours <- parse_json(raw_colours)
colours
```
```{r}
class(colours[1])
```
##some lists can then be converted to dataFrames, some cant.
```{r}
colours2 <- fromJSON(raw_colours)
colours2
```
#column "code" can be expanded:
```{r}
library(tidyverse)
unnest(colours2$code)
```

```{r}
read_example <- read_file("3_json_files/data/example.json")
prettify(read_example)
read_example1 <- parse_json(read_example)
read_example2 <- fromJSON(read_example1)
read_example2
```
##write JSON
```{r}
library(CodeClanData)
```
```{r}
colour_list
```
```{r}
write_json(colour_list, "colours2.json", pretty = TRUE, auto_unbox = TRUE)
```
```{r}
library(readr)
locale()
```
```{r}
#can be used to change encoding
#locale(encoding = "Latin1")

```

```{r}
p_n_p_default <- read_file("4_parsing_data/data/pride_and_prejudice_utf_16.txt")
p_n_p_default
p_n_p_utf16 <- read_file("4_parsing_data/data/pride_and_prejudice_utf_16.txt", locale = locale(encoding = "UTF-16"))
p_n_p_utf16
```

```{r}
cake <- read_delim("4_parsing_data/data/cake_european.csv", delim = ";")
cake
```
```{r}
cake_decimal <- read_delim("4_parsing_data/data/cake_european.csv", delim = ";", locale = locale(decimal_mark = ",", date_format = "%d/%m/%Y"))
#cake_decimal <- (cake, )
cake_decimal
```





























