---
title: "Decision Trees"
output: html_notebook
---

```{r}
library(rpart)
library(rpart.plot)
library(tidyverse)
```

```{r}
thrones <- read_csv("data/character_data_S01-S08.csv")
head(thrones)
```

Columns need to be factors or numerics, so that the data is labelled. 

```{r}
clean_thrones<- thrones %>% 
# Only keep variables of interest
  select(c(sex, religion, occupation, social_status, allegiance_last, allegiance_switched, dth_flag, featured_episode_count, prominence)) %>% 
# Convert to factor level
    mutate(sex = factor(sex, levels = c(1, 2, 9), labels = c("Male", "Female", "Unknown")),
    religion = factor(religion, levels = c(0, 1, 3, 4, 5, 6, 7, 9), labels = c("Great Stallion", "Lord of Light", "Faith of the Seven", "Old Gods", "Drowned God", "Many Faced God", "Other", "Unknown")),
    occupation = factor(occupation, levels = c(1, 2, 9), labels = c("Silk-collar", "Leather-collar", "Unknown")),
    social_status = factor(social_status, levels = c(1, 2, 9), labels = c("Highborn", "Lowborn", "Unknown")),
    allegiance_last = factor(allegiance_last, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9), labels = c("Stark", "Targaryen", "Night's Watch", "Lannister", "Greyjoy", "Bolton", "Frey", "Other", "Unknown")),
    allegiance_switched = factor(allegiance_switched, levels = c(1, 2, 9), labels = c("No", "Yes", "Unknown")),
    dth_flag = factor(dth_flag, levels = c(0, 1), labels = c("Survived", "Died"))) %>%
# Remove NAs 
 na.omit()

head(clean_thrones)
```

```{r}
dim(clean_thrones)
```

#train/test split

```{r}
n_data <- nrow(clean_thrones)

test_index <- sample(1:n_data, size = n_data*0.2)

thrones_test <- slice(clean_thrones, test_index)

thrones_train <- slice(clean_thrones, -test_index)
```

```{r}
library(janitor)
```

#test for balance

```{r}
thrones_test %>%
  tabyl(dth_flag)
```
```{r}
thrones_train %>%
  tabyl(dth_flag)
```

```{r}
thrones_fit<- rpart(dth_flag ~ . ,
                    data = thrones_train, 
                    method = "class")
thrones_fit
```

Plot

Blue = low probability,
Green = high probability.

```{r}
rpart.plot(thrones_fit, yesno = 2)
```
```{r}
rpart.rules(thrones_fit, cover = TRUE)
```

# Create predictions and check them on test data
```{r}
library(modelr)
```

```{r}
thrones_test_pred <- thrones_test %>%
  add_predictions(thrones_fit, type = "class")
thrones_test_pred
```
```{r}
rpart.predict(thrones_fit, newdata = thrones_test[1:3, ], rules = FALSE)
```

# check model performance.

```{r}
library(yardstick)
```

```{r}
conf_matrix <- thrones_test_pred %>%
  conf_mat(truth = dth_flag, estimate = pred)
conf_matrix
```

# accuracy scores

```{r}
accuracy_death <- thrones_test_pred %>%
  accuracy(truth = dth_flag, estimate = pred)
accuracy_death
```

