---
title: "R Notebook"
output: html_notebook
---
Create a DataFrame
```{r}
student <- c("Abigail", "Bjorn", "Caitlin", "Dave", "Elly", "Francis")
question_1 <- c(10, 3, 1, 5, 5, 8)
question_2 <- c(2, 5, 5, 4, 5, 6)
question_3 <- c(4, 5, 9, 7, 6, 8)
```
```{r}
exam_results <- data.frame(student, question_1, question_2, question_3)
```
```{r}
exam_results$question_1
```
```{r}
#add a column
exam_results$question_4 <- c(6L, 3L, 10L, 3L, 9L, 7L)
exam_results
#to wipe question_4
exam_results$question_4 <- NULL
exam_results

```
```{r}
exam_results$total <- exam_results$question_1 + exam_results$question_2 + exam_results$question_3
exam_results
```
Quick text summary of a DataFrame
```{r}
str(exam_results)
```
```{r}
View(exam_results)
```
```{r}
nrow(exam_results)#number or rows
ncol(exam_results)#number of columns
#for both ncol & nrow
dim(exam_results)
```
```{r}

exam_results[1, ]#selects first row, all columns
exam_results[,1]#selects values from the first column (in a flat way)
```
```{r}
exam_results[1,1]
```
```{r}
exam_results[3:5, ]
```
```{r}
exam_results[c(1, 3, 5), ]
```
```{r}
exam_results$student
#same as
exam_results[ ,"student"]
#same as
exam_results[ ,1]
```
```{r}
exam_results[ ,c("student", "question_1")]
```
```{r}
#use subset function if we want to filter by a specific condition
subset(exam_results, question_2 == 5)
```
```{r}
colnames(exam_results)
rownames(exam_results)
```
```{r}
rownames(exam_results) <- c("student_1", "student_2", "student_3", "student_4", "student_5", "student_6")
exam_results
```
```{r}
results_order <- order(exam_results$total)
results_order
```
```{r}
exam_results$total
```
```{r}
exam_results[results_order, ]
```

```{r}
age <- c(25, 56, 40)
gender <- c("female", "female", "male")
shoe_size <- c(7, 5, 13)
is_satisfied <- c(TRUE, TRUE, FALSE)
shoe_satisfaction <- data.frame(age, gender, shoe_size, is_satisfied)
```
Select the first row of shoe_satisfaction.
Select the third column of shoe_satisfaction.
Select the rows of shoe_satisfaction that correspond to satisfied customers.
Sort the data frame by ascending age.
```{r}
shoe_satisfaction
```
```{r}
shoe_satisfaction[1, ]
```
```{r}
shoe_satisfaction[ ,3]
```
```{r}
subset(shoe_satisfaction, is_satisfied == TRUE)
```
```{r}
age_order <- order(shoe_satisfaction$age)
shoe_satisfaction[age_order, ]
```
Lists
```{r}
x <- list(1, "a", TRUE, c(1, 2, 3))
x
```
```{r}
x[[2]]
```
```{r}
x[2]
```
```{r}
named_list <- list(a = "I love R", b = 1:10)
named_list
```
```{r}
named_list$a
names(named_list)
```

```{r}
student_info <- list(
                "Agnes" = list(height = 1.8, shoe_size = 8L),
                "Bobby" = list(height = 2.1, gender = "Male"),
                "Charlie" = list(gender = "Female", likes_beets = TRUE)
)
student_info
```
```{r}
student_info$Agnes$height
#same as 
student_info[[1]][[1]]
```
```{r}
named_list1 <- list(numbers = 1:3,  words = c("one", "two", "three"))
named_list1
```
```{r}
class(named_list1[[2]])
class(named_list1[2])
class(named_list1$words)
```
```{r}
my_matrix <- matrix(rep(1:3,4), nrow = 3, ncol = 4)
my_matrix
```
```{r}
dim(my_matrix)
colSums(my_matrix)
rowSums(my_matrix)
rownames(my_matrix) <- c("one", "two", "three")
my_matrix
```
```{r}
another_matrix <- data.frame(
  c1 = c(1, 2 , 3),
  c2 = c("A", "B", "C"),
  stringsAsFactors = FALSE #this creates characters as chars, not factors
)
another_matrix
```
```{r}
class(another_matrix$c1)
class(another_matrix$c2)
```
```{r}
dataframe_example <- data.frame(
  c1 = 1:5,
  c2 = LETTERS[6:10],
  c3 = 11:15
)
dataframe_example
```

```{r}
class(as.matrix(dataframe_example))
```
```{r}
class(data.matrix(dataframe_example))
```












