---
title: "Functions"
output: html_notebook
---
# USEFUL FUNCTIONS

```{r}
#absolute values - returns a positive number
abs(-2.2)
```
```{r}
#round
round(5.1234567890) #by default rounds to 0 dp
round(5.1234567890, digits = 2)
```
```{r}
#always rounds down
floor(5.9)
```
```{r}
#round up
ceiling(6.1)
```
# FOR CHARACTERS ONLY
```{r}
#concatenation
paste("Hello", "Bye")
paste0("Hello", "Bye")
```
```{r}
paste(letters, collapse = " ")
```
#SORTING
```{r}
sort(c("c", "f", "a"), decreasing = TRUE)
```
```{r}
#number of chsrs
nchar("hello")
nchar(c("hello", "bye"))
```
# CUSTOM FUNCTIONS

function_name <- function(arg1, arg2,...)
do_code
return(output)
```{r}
by_five <- function(x) {
  return(x * 5)
}

by_five(10)
```
```{r}
#multiple inputs
mult <- function(x, y=5) {
  return(x * y)
}
mult(2, 3)
mult(2)
```
```{r}
make_price <- function(x) {
  paste0("£", x)
}
make_price(123)
```

```{r}
animals <- c("Cat", "Dog", "Monkey", "Elephant", "Frog")
hats <- c("Bowler", "Sun Hat", "Baseball Cap", "Fez")
trees <- c("Ash", "Elm", "Oak", "Willow", "Fir")
```
```{r}
animals_sorted <- sort(animals)
animals_joined <- paste(animals_sorted, collapse = " ")
paste("Ordered list:", animals_joined)
```
```{r}
make_ordered_list <- function(my_list) {
  my_list_sorted <- sort(my_list)
  my_list_joined <- paste(my_list_sorted, collapse = ", ")
  paste("Ordered list:", my_list_joined)
}

make_ordered_list(animals)
make_ordered_list(hats)
make_ordered_list(trees)
```
```{r}
debugonce((make_ordered_list))
make_ordered_list(hats)
```
```{r}
library(tidyverse)
```

```{r}

make_fancy_price <- function(x = NULL){
  if (!is.null(x)) {
  char <- as.character(x)
  price <<- stringi::stri_split_fixed(char,".")
  case_when(
    price[[1]][1] == "0" ~ paste(price[[1]][2], "pence"),
    is.na(price[[1]][2]) ~ paste(price[[1]][1], "pounds"),
    TRUE ~ paste(price[[1]][1], "pounds", price[[1]][2], "pence")
    )
  } else {
      paste("Please enter price")
  }
}
make_fancy_price(123.25)
```
```{r}
price
```
























