---
title: "Week 2 day 2"
output: html_notebook
---
Below script creates a path to R credentials.
```{r}
home_location <- Sys.getenv("HOME")
credentials_location <- paste0(home_location,"/credentials.R")
source(credentials_location) #this loads the credentials into R Environment
```
Connect to a database
```{r}
#install.packages("RPostgreSQL")
library(RPostgreSQL)
```

```{r}

my_db_connection <- dbConnect(drv = PostgreSQL(max.con = 1), user = postgresql_username, password = postgresql_password, dbname = 'omni_employees', host = 'localhost')
```
Working with the database
```{r}
dbListTables(conn = my_db_connection)
```
```{r}
dbListFields(conn = my_db_connection, name = "employees")
```
```{r}
data <- dbGetQuery(conn = my_db_connection, statement = "SELECT * FROM employees")
data
```

```{r}
dbGetQuery(conn = my_db_connection, statement = 
           "UPDATE employees SET email = 'sadame3@utexas.edu' WHERE id = 3;
           SELECT * FROM employees WHERE id = 3")
```



```{r}
# this closes db connection 
dbDisconnect(conn = my_db_connection)
```
Connecting to a remote database, credentials file already update with remote username & password
```{r}
home_location <- Sys.getenv("HOME")
credentials_location <- paste0(home_location,"/credentials.R")
source(credentials_location) #this loads the credentials into R Environment
```
```{r}
db_connect <- dbConnect(drv = PostgreSQL(max.con = 1), user = remote_omni_postgresql_username, password = remote_omni_postgresql_username, dbname='cjitjeca', host='34.245.37.126')
```
```{r}
dbListTables(conn = db_connect)
```

```{r}
dbGetQuery(conn = db_connect, statement = 
             "SELECT * FROM cjitjeca")
```
```{r}
# this closes db connection 
dbDisconnect(conn = db_connect)
```




