---
title: '`dplyr` practice : answers'
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    css: ../../../styles.css
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=TRUE, fig.align = 'center')
```


**Duration: 1 hour**

<br>

You now have an opportunity to practice the skills you've learnt today in a mini lab task. 

For this you will be using data which contains income generated by US states from year 2002 to 2015. Note : The data do not contain actual income figures of the states. This can be found in the  `state_income_data.csv` file that we have uploaded into the data folder. 

<br>

**Question 1**

Load in the data, and have a look at it. How many variables does it have? How many observations? What are the variable names? What type of variables does it have?  

<br>


**Question 2**  

Select the columns which contain the information from years `2002` to `2008`. Ensure you keep the `Index` and `State` variables as well.  

<br>



**Question 3**  

Rename the `Index` column to `first_letter`. *Hint: look up the `rename()` function*. 

<br>


**Question 4**  

Find the seven states which start with an `A`,`B`, or `C`. 

<br>


**Question 5**  

Find which of these seven states have the greatest income in 2008.  
<br>




**Question 6**  

Calculate the change in income for each state of these seven states (states starting with `A`,`B`, or `C`) between 2002 and 2008. Save the income change in a new column called `income_change`.   

<br>



**Question 7**  

Find which of these seven states income change is greater than 500,000 (i.e. an increase of 500,000 or decrease of 500,000).  
 

<br>



**Question 8**  

Calculate the mean and median income change for all seven states.

<br>




**Question 9**  

Go back to the original dataset which contains all states. Write a pipe which selects the `State` and `Y2008` variables, arranges the income from highest to lowest, filters all those states which have a income of greater than 1 million, and then finally chooses the top 10 wealthiest states.  
<br>
